route:
    receiver: 'mattermost'

receivers:
    - name: 'mattermost'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#<channel-name>'
            api_url: 'https://hur-quest-40:9443/hooks/<webhook-id>'
